# Simplify running the application inside a container locally.
# Usage: `docker-compose up`
#
# Do not use docker-compose in production environments.

# The API is expected to be up on port 5000 of the host machine

version: '3'

services:
  redis:
    image: redis
  web:
    build: .
    env_file: .env
    environment:
      - REDIS_URL=redis://redis:6379
      - API_BASE_URL=http://host.docker.internal:5000
    ports:
      - "3000:3000"
    depends_on:
      - redis
