version: 2.1

aliases:
  - &node_version               circleci/node:11

  # Common steps
  - &install_dependencies
    run:
      name: Install NPM dependencies
      command: npm install
  - &restore_cache
    restore_cache:
      name: Restore NPM cache
      key: dependency-cache-{{ checksum "package.json" }}
  - &save_cache
    save_cache:
      name: Save NPM cache
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules

jobs:
  build:
    docker:
      - image: *node_version
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run: npm run build
  lint:
    docker:
      - image: *node_version
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run: npm run lint
  unit_test:
    docker:
      - image: *node_version
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run: npm test

workflows:
  pecs-frontend:
    jobs:
      - build
      - lint
      - unit_test
