version: 2.1

orbs:
  slack: circleci/slack@3.4.2

aliases:
  # Shared containers
  - &circle_container
    docker:
      - image: circleci/node:12-browsers
  - &cloud_container
    docker:
      - image: ${ECR_ENDPOINT}/cloud-platform/tools:circleci
        environment:
          GITHUB_TEAM_NAME_SLUG: book-a-secure-move
  # Common steps
  - &install_dependencies
    run:
      name: Install NPM dependencies
      command: npm install && npm rebuild node-sass
  - &restore_cache
    restore_cache:
      name: Restore NPM cache
      key: dependency-cache-{{ checksum "package.json" }}
  - &save_cache
    save_cache:
      name: Save NPM cache
      key: dependency-cache-{{ checksum "package.json" }}
      paths:
        - ./node_modules
  - &set_package_version
    run:
      name: Set version
      command: |
        echo "export PACKAGE_VERSION=$(grep -m1 version package.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')" >> $BASH_ENV
  - &notify_slack_on_failure
    slack/notify-on-failure:
      only_for_branches: master
  - &notify_slack_on_release_start
    slack/notify:
      channel: $BUILD_NOTIFICATIONS_CHANNEL_ID
      title: 'Frontend v${PACKAGE_VERSION} is being prepared for release :building_construction:'
      title_link: 'https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/blob/master/CHANGELOG.md'
      message: A new release was created by ${CIRCLE_USERNAME}
      footer: Click the title to view the changes
      include_project_field: false
      include_job_number_field: false
      include_visit_job_action: false
      color: '#1d70b8'
      mentions: here
  - &notify_slack_of_approval
    slack/approval:
      channel: $BUILD_NOTIFICATIONS_CHANNEL_ID
      message: 'Frontend v${PACKAGE_VERSION} *requires your approval* before it can be deployed :eyes:'
      include_project_field: false
      include_job_number_field: false
      color: '#912b88'
      mentions: $BUILD_NOTIFICATIONS_MENTION_ID
  - &notify_slack_on_release_end
    slack/notify:
      channel: $BUILD_NOTIFICATIONS_CHANNEL_ID
      title: 'Frontend v${PACKAGE_VERSION} has been deployed :rocket:'
      title_link: https://github.com/ministryofjustice/hmpps-book-secure-move-frontend/releases/tag/v${PACKAGE_VERSION}
      message: This release was successfully deployed to production
      footer: Click the title to view the release notes
      include_project_field: false
      include_job_number_field: false
      include_visit_job_action: false
      color: '#28a197'
      mentions: here
  # Common filters
  - &all_tags
    filters:
      tags:
        only: /.*/
  - &only_master_and_tags
    filters:
      tags:
        only: /.*/
      branches:
        only: master
  - &only_deploy_tags
    filters:
      tags:
        only: /^v.*/
      branches:
        ignore: /.*/
  - &requires_production_approval
    requires:
    - production_approval

commands:
  build_for_k8s:
    description: 'Builds a Docker image for staging/production and pushes to ECR'
    parameters:
      env:
        type: string
      notify_slack:
        type: string
        default: ""
    steps:
      - checkout
      - *set_package_version
      - when:
          condition: <<parameters.notify_slack>>
          steps:
            - *notify_slack_on_release_start
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build docker image
          command: |
            export BUILD_DATE=$(date -Is) >> $BASH_ENV
            source $BASH_ENV

            docker build \
              --label build.git.sha=${CIRCLE_SHA1} \
              --label build.git.branch=${CIRCLE_BRANCH} \
              --label build.date=${BUILD_DATE} \
              --build-arg APP_BUILD_DATE=${BUILD_DATE} \
              --build-arg APP_BUILD_TAG=${CIRCLE_BRANCH} \
              --build-arg APP_GIT_COMMIT=${CIRCLE_SHA1} \
              -t app .
      - run:
          name: Push docker image
          command: |
            login="$(aws ecr get-login --region ${AWS_DEFAULT_REGION} --no-include-email)"
            ${login}

            docker tag app "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"
            docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"

            docker tag app "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:<< parameters.env >>.latest"
            docker push "${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:<< parameters.env >>.latest"

  deploy_to_k8s:
    description: 'Deploys a previously built Docker image to staging/production k8s environment'
    parameters:
      env:
        type: string
    steps:
      - checkout
      - *set_package_version
      - run:
          name: Set k8s context
          command: |
            setup-kube-auth
            kubectl config use-context << parameters.env >>
      - deploy:
          name: Deploy image to << parameters.env >>
          command: |
            export BUILD_DATE=$(date -Is) >> $BASH_ENV
            source $BASH_ENV

            kubectl set image -n hmpps-book-secure-move-frontend-<< parameters.env >> \
                    deployment/hmpps-book-secure-move-frontend-deployment-<< parameters.env >> \
                    webapp="${ECR_ENDPOINT}/${GITHUB_TEAM_NAME_SLUG}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}"

            kubectl annotate -n hmpps-book-secure-move-frontend-<< parameters.env >> \
                    deployment/hmpps-book-secure-move-frontend-deployment-<< parameters.env >> \
                    kubernetes.io/change-cause="${BUILD_DATE} set image ${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} via CircleCI"

jobs:
  notify-of-approval:
    <<: *circle_container
    steps:
      - checkout
      - *set_package_version
      - *notify_slack_of_approval

  build_and_test:
    <<: *circle_container
    steps:
      - checkout
      - *set_package_version
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: Lint the code
          command: npm run circle:lint
      - run:
          name: Setup Code Climate test-reporter
          # download test reporter as a static binary
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Notify CodeClimate before build
          command: |
            ./cc-test-reporter before-build
          when: always
      - run:
          name: Run unit tests
          command: |
            npm run circle:coverage
      - run:
          name: Upload coverage to CodeClimate
          command: |
            ./cc-test-reporter after-build
          when: always
      - run:
          name: Build the app
          command: NODE_ENV=production npm run build
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: coverage
      - *notify_slack_on_failure

  e2e_test:
    <<: *circle_container
    steps:
      - checkout
      - *set_package_version
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: Run E2E tests
          command: npm run test-e2e:ci
      - store_test_results:
          path: reports/testcafe
      - store_artifacts:
          path: artifacts
      - *notify_slack_on_failure

  publish_release_to_github:
    <<: *circle_container
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache
      - run:
          name: Publish release to GitHub
          command: npm run release:github

  build_staging:
    <<: *cloud_container
    steps:
      - build_for_k8s:
          env: 'staging'

  deploy_staging:
    <<: *cloud_container
    steps:
      - deploy_to_k8s:
          env: 'staging'

  build_preprod:
    <<: *cloud_container
    steps:
      - build_for_k8s:
          env: 'preprod'

  deploy_preprod:
    <<: *cloud_container
    steps:
      - deploy_to_k8s:
          env: 'preprod'

  build_production:
    <<: *cloud_container
    steps:
      - build_for_k8s:
          env: 'production'
          notify_slack: 'true'

  deploy_production:
    <<: *cloud_container
    steps:
      - deploy_to_k8s:
          env: 'production'
      - *notify_slack_on_release_end

workflows:
  frontend:
    jobs:
      - build_and_test:
          <<: *all_tags
      - build_staging:
          <<: *only_master_and_tags
      - build_preprod:
          <<: *only_master_and_tags
          requires:
          - build_and_test
      - deploy_staging:
          <<: *only_master_and_tags
          requires:
          - build_and_test
          - build_staging
      - deploy_preprod:
          <<: *only_master_and_tags
          requires:
          - build_preprod
          - e2e_test
      - e2e_test:
          <<: *only_master_and_tags
          requires:
          - deploy_staging
      - build_production:
          <<: *only_deploy_tags
          requires:
          - build_and_test
      - production_approval:
          <<: *only_deploy_tags
          type: approval
          requires:
          - e2e_test
      - notify-of-approval:
          <<: *only_deploy_tags
          requires:
          - e2e_test
      - publish_release_to_github:
          <<: *only_deploy_tags
          <<: *requires_production_approval
      - deploy_production:
          <<: *only_deploy_tags
          <<: *requires_production_approval
